<?php

/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-lang/de/qa-lang-main.php
	Version: 1.8
	Date: 2019-09-25
	Description: Language phrases commonly used throughout Q2A in German
	Translation: Peter Chiochetti, Moritz Bunkus, Philip Schilling, Corinna Baldauf, Fulgor@github

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
	    '1_answer' => '1 Jawaban',
'1_comment' => '1 komentar',
'1_day' => '1 Hari',
'1_disliked' => '1 Tidak Suka',
'1_flag' => '1 Tag',
'1_hour' => '1 Jam',
'1_liked' => '1 Suka',
'1_minute' => '1 Menit',
'1_month' => '1 Bulan',
'1_point' => '1 Poin',
'1_question' => '1 Pertanyaan',
'1_second' => '1 Detik',
'1_tag' => '1 hari',
'1_user' => '1 Pengguna',
'1_view' => '1 Dilihat',
'1_vote' => '1 Suara',
'1_week' => '1 Minggu',
'1_year' => '1 Tahun',
'add_category_x_favorites' => 'Tambahkan kategori ^ ke favorit saya',
'add_favorites' => 'Tambahkan ke favorit saya',
'add_tag_x_favorites' => 'Tambahkan tag ^ ke favorit saya',
'all_categories' => 'Semua KATEGORI',
'anonymous' => 'Anonim',
'answer_edited' => 'Jawaban telah diedit',
'answer_reshown' => 'Jawaban ditampilkan lagi',
'answer_selected' => 'Jawaban dipilih',
'answered' => 'dijawab',
'answered_qs_in_x' => 'Pertanyaan yang paling sering dijawab di ^',
'answered_qs_title' => 'Pertanyaan yang paling sering dijawab',
'asked' => 'Ditanyakan',
'asked_related_q' => 'Ajukan pertanyaan terkait',
'by_x' => 'oleh ^',
'cancel_button' => 'Batalkan',
'closed'  => 'tertutup',
'comment_edited' => 'Komentar telah diedit',
'comment_moved' => 'Komentar dipindahkan',
'comment_reshown' => 'Komentar ditampilkan lagi',
'commented' => 'Berkomentar',
'date_day_min_digits' => 1, // 1 atau 2
'date_format_other_years' => '^day ^month ^year',
'date_format_this_year' => '^day ^month',
'date_month_1' => 'Jan',
'date_month_10' => 'Okt',
'date_month_11' => 'Nov',
'date_month_12' => 'Des',
'date_month_2' => 'Feb',
'date_month_3' => 'Mar',
'date_month_4' => 'Apr',
'date_month_5' => 'Mei',
'date_month_6' => 'Juni',
'date_month_7' => 'Jul',
'date_month_8' => 'Agustus',
'date_month_9' => 'Sep',
'date_year_digits' => 4, // 2 atau 4
'edited'  => 'diedit',
'email_error' => 'Kesalahan saat mencoba mengirim email.',
'field_required' => 'Silakan masukkan sesuatu di kolom',
'file_upload_limit_exceeded' => 'Ukuran file melebihi nilai yang diizinkan',
'general_error' => 'Kesalahan sisi server - silakan coba lagi',
'hidden' => 'tersembunyi',
'highest_users' => 'Pengguna dengan Skor tertinggi',
'hot_qs_in_x' => 'Pertanyaan populer di ^',
'hot_qs_title' => 'Pertanyaan populer',
'image_not_read' => 'Gambar tidak dapat dibaca. Silakan unggah salah satu dari: ^ ',
'image_too_big_x_pc' => 'Gambar terlalu besar. Harap kurangi menjadi ^% dan coba lagi. ',
'in_category_x' => 'di ^',
'ip_address_x' => 'Alamat IP ^',
'login_x' => 'Login pada ^',
'max_length_x' => 'Maksimum ^ karakter diperbolehkan',
'max_upload_size_x' => 'Maksimum yang diperbolehkan adalah ^',
'me' => 'saya',
'meta_order' => '^what^when^where^who', // mengatur urutan elemen seperti: <answered> <15 jam yang lalu> <dalam Masalah> <oleh saya (500 poin)>
'min_length_x' => 'Harap lebih detail - setidaknya ^ karakter',
'moved' => 'pindah',
'nav_activity' => 'Aktifitas',
'nav_admin' => 'Admin',
'nav_ask' => 'Tanya Sesuatu',
'nav_categories' => 'Kategori',
'nav_feedback' => 'Komentar dan saran',
'nav_home' => 'Mulai',
'nav_hot' => 'Populer!',
'nav_login' => 'Masuk',
'nav_logout' => 'Keluar',
'nav_most_answers' => 'Balasan terbanyak',
'nav_most_recent' => 'Baru',
'nav_most_views' => 'Terbanyak Dilihat',
'nav_most_votes' => 'Suara terbanyak',
'nav_no_answer' => 'Tidak ada jawaban',
'nav_no_selected_answer' => 'Tidak ada jawaban yang dipilih',
'nav_no_upvoted_answer' => 'Tidak ada tanggapan dengan penilaian positif',
'nav_qa' => 'Beranda',
'nav_qs' => 'Pertanyaan',
'nav_register' => 'Daftar',
'nav_tags' => 'Tags',
'nav_unanswered' => 'Belum Dijawab',
'nav_updates' => 'Berita',
'nav_users' => 'Pengguna',
'no_active_users' => 'Tidak ditemukan akun aktif',
'no_answers_found' => 'Tidak ada jawaban yang ditemukan',
'no_answers_in_x' => 'Tidak ada jawaban di ^',
'no_categories_found' => 'Tidak ada kategori yang ditemukan',
'no_category' => 'Tidak ada kategori',
'no_comments_found' => 'Tidak ada komentar yang ditemukan',
'no_comments_in_x' => 'Tidak ada komentar di ^',
'no_questions_found' => 'Tidak ada pertanyaan yang ditemukan',
'no_questions_in_x' => 'Tidak ada pertanyaan di ^',
'no_related_qs_title' => 'Tidak ditemukan pertanyaan serupa',
'no_results_for_x' => 'Tidak ada hasil untuk ^',
'no_tags_found' => 'Tidak ditemukan tag',
'no_una_questions_found' => 'Tidak ditemukan pertanyaan yang belum terjawab',
'no_una_questions_in_x' => 'Tidak ada pertanyaan yang belum terjawab di ^',
'no_unselected_qs_found' => 'Tidak ada pertanyaan tanpa jawaban yang dipilih ditemukan',
'no_unupvoteda_qs_found' => 'Tidak ditemukan pertanyaan tanpa jawaban dengan peringkat positif',
'page_label' => 'Halaman:',
'page_next' => 'berikutnya',
'page_not_found' => 'Halaman tidak ditemukan',
'page_prev' => 'sebelumnya',
'popular_tags' => 'Tag Terpopuler',
'questions_tagged_x' => 'Pertanyaan dengan tag ^',
'recategorized' => 'Kategori diubah',
'recent_activity_in_x' => 'Aktivitas terakhir di ^',
'recent_activity_title' => 'Aktivitas terbaru',
'recent_as_in_x' => 'Terakhir dijawab di ^',
'recent_as_title' => 'Terakhir dijawab',
'recent_cs_in_x' => 'Komentar terbaru di ^',
'recent_cs_title' => 'Komentar Terbaru',
'recent_qs_as_in_x' => 'Pertanyaan & jawaban terbaru di ^',
'recent_qs_as_title' => 'Tanya Jawab Terkini',
'recent_qs_in_x' => 'Pertanyaan terbaru di ^',
'recent_qs_title' => 'Pertanyaan terbaru',
'related_qs_title' => 'Pertanyaan serupa',
'remove_favorites' => 'Hapus dari favorit saya',
'remove_x_favorites' => 'Hapus ^ dari favorit saya',
'reopened' => 'dibuka kembali',
'reshown' => 'ditampilkan kembali',
'results_for_x' => 'Hasil pencarian untuk ^',
'retagged' => 'diberi tag kembali',
'save_button' => 'Simpan perubahan',
'search_button' => 'Cari pertanyaan',
'search_explanation' => 'Silakan masukkan beberapa teks di kotak pencarian dan coba kembali.',
'search_title' => 'Cari pertanyaan',
'selected' => 'dipilih',
'answer_reshown' => "jawaban ditampilkan kembali",
'comment_reshown' => "komentar ditampilkan kembali",
'logged_in_x' => "Hi ^",
'send_button' => 'Kirim',
'since_x' => 'sejak ^',
'suggest_ask' => 'Mulailah ^1ajukan pertanyaan^2.',
'suggest_category_qs' => '^1Tampilkan semua pertanyaan dalam kategori ini ^2.',
'suggest_qs' => '^1 Lihat Semua Pertanyaan ^2.',
'suggest_qs_tags' => '^1 Lihat semua pertanyaan ^2 atau ^3lihat Tag yang populer ^4.',
'to_x' => 'ke ^',
'unanswered_qs_in_x' => 'Belum terjawab dalam ^',
'unanswered_qs_title' => 'Pertanyaan Belum Terjawab',
'unselected_qs_in_x' => 'Pertanyaan tanpa jawaban yang dipilih di ^',
'unselected_qs_title' => 'Pertanyaan yang baru saja diajukan tanpa jawaban yang dipilih',
'unupvoteda_qs_in_x' => 'Pertanyaan tanpa jawaban dengan evaluasi positif di ^',
'unupvoteda_qs_title' => 'Pertanyaan yang baru saja diajukan tanpa jawaban dengan penilaian positif',
'upload_limit' => 'Terlalu banyak upload - coba lagi dalam satu jam.',
'view_q_must_be_approved' => 'Akun Anda harus disetujui untuk melihat pertanyaan. Harap tunggu atau ^1 tambahkan informasi lebih lanjut ^2. ',
'view_q_must_confirm' => 'Harap ^5konfirmasi alamat email Anda ^6 untuk membuka halaman pertanyaan.',
'view_q_must_login' => 'Silakan ^1 login ^2 atau ^3 daftar ^4 untuk membuka halaman pertanyaan.',
'viewed_qs_in_x' => 'Pertanyaan yang paling banyak dilihat di ^',
'viewed_qs_title' => 'Pertanyaan yang paling banyak dilihat',
'vote_disabled_approve' => 'Akun Anda harus disetujui untuk diberi peringkat.',
'vote_disabled_down' => 'Hanya akun tertentu yang diizinkan untuk melakukan devaluasi',
'vote_disabled_down_approve' => 'Akun Anda harus disetujui untuk devaluasi',
'vote_disabled_hidden_a' => 'Anda tidak dapat memberikan poin untuk jawaban yang disembunyikan',
'vote_disabled_hidden_q' => 'Anda tidak dapat memberikan poin untuk pertanyaan tersembunyi',
'vote_disabled_level' => 'Peringkat hanya tersedia untuk pengguna tertentu',
'vote_disabled_my_a' => 'Anda tidak dapat memberikan poin untuk jawaban Anda sendiri',
'vote_disabled_my_q' => 'Anda tidak dapat memberikan poin untuk pertanyaan Anda sendiri',
'vote_disabled_q_page_only' => 'Silakan periksa pertanyaan untuk memberikan poin',
'vote_down_must_confirm' => 'Harap ^5 konfirmasi alamat email Anda ^6 untuk memberikan penilaian negatif.',
'vote_down_popup' => 'Berikan poin minus',
'vote_limit' => 'Menerima terlalu banyak poin - coba lagi dalam satu jam',
'vote_must_confirm' => 'Harap ^5 konfirmasi alamat email Anda ^6 untuk mendapatkan poin.',
'vote_must_login' => 'Silakan ^1 login ^2 atau ^3 daftar ^4 untuk mendapatkan poin.',
'vote_not_allowed' => 'Anda tidak dapat memberikan poin apa pun untuk ini',
'vote_up_popup' => 'Berikan nilai plus',
'voted_down_popup' => 'Anda telah memberikan poin minus - hapus poin minus',
'voted_qs_in_x' => 'Pertanyaan dengan ulasan paling positif di ^',
'voted_qs_title' => 'Pertanyaan berperingkat teratas',
'voted_up_popup' => 'Anda telah memberikan poin plus - ambil kembali poin plus',
'written' => '',
'x_ago' => '^ lalu',
'x_answers' => '^ Jawaban',
'x_comments' => '^ Komentar',
'x_days' => '^ Hari',
'x_disliked' => '^ Tidak Suka',
'x_flags' => '^ Tag',
'x_hours' => '^ Jam',
'x_liked' => '^ Suka',
'x_minutes' => '^ Menit',
'x_months' => '^ Bulan',
'x_points' => '^ Poin',
'x_questions' => '^ Pertanyaan',
'x_seconds' => '^ Detik',
'x_tags' => '^ Tags',
'x_users' => '^ Pengguna',
'x_views' => '^ Dilihat',
'x_votes' => '^ Suara',
'x_weeks' => '^ Minggu',
'x_years' => '^ Tahun',
'_decimal_point' => ".",
    '_millions_suffix' => "jt",
    '_thousands_separator' => ",",
    '_thousands_suffix' => "rb",
    'newest_users' => "Pengguna Terkini",
    'vote_disabled_hidden_post' => "Anda tidak dapat menilai entri tersembunyi",
    'vote_disabled_my_post' => "Anda tidak dapat menilai posting Anda sendiri",
    'vote_disabled_queued' => "Anda hanya dapat menilai entri yang dikonfirmasi",
	);
/*
	Omit PHP closing tag to help avoid accidental output
*/
