<?php
/*
    Question2Answer by Gideon Greenspan and contributors
    http://www.question2answer.org/

    File: qa-lang/de/qa-lang-admin.php
    Version: 1.8
    Date: 2019-10-23
    Description: Language phrases for admin center in formal German (Sie)
    Translation: Fulgor@github

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
'active_widgets_explanation' => 'Widget yang aktif saat ini:',
'add_category_button' => 'Tambahkan kategori',
'add_field_button' => 'Tambah bidang',
'add_link_button' => 'Tambahkan tautan',
'add_link_link' => '- ^1 tambahkan tautan ^2',
'add_new_field' => 'Tambah bidang baru',
'add_new_title' => 'Tambahkan judul baru',
'add_page_button' => 'Tambahkan halaman',
'add_title_button' => 'Tambahkan judul',
'add_widget_button' => 'Tambahkan widget',
'add_widget_link' => '- ^1 tambahkan widget ^2',
'admin_title' => 'Administrasi',
'after_footer' => 'Ke kiri di area footer',
'after_main_menu' => 'Setelah tab atas',
'after_x' => 'Setelah "^"',
'after_x_tab' => 'Setelah Tab "^"',
'approve_user_popup' => 'Setujui pengguna',
'approve_users_title' => 'Setujui pengguna',
'basic_editor' => 'Editor Dasar',
'before_main_menu' => 'Sebelum tab atas',
'blobs_directory_error' => 'Direktori ^ yang didefinisikan sebagai QA_BLOBS_DIRECTORY tidak memiliki izin menulis di server.',
'blobs_move_complete' => 'Transfer gambar dan dokumen yang diunggah ditutup.',
'blobs_move_moved' => 'Transfer ^1 dari ^2 gambar dan dokumen yang diunggah',
'blobs_stop' => 'Transfer dihentikan',
'blobs_to_db' => 'Blob ke database',
'blobs_to_db_note' => '- transfer semua gambar dan dokumen yang diunggah ke database',
'blobs_to_disk' => 'Blob ke disk',
'blobs_to_disk_note' => '- transfer semua gambar dan dokumen yang diunggah dari database ke hard drive',
'block_button' => 'blok',
'block_ips_note' => 'Gunakan "-" untuk area atau "*" sebagai variabel untuk setiap angka. Contoh: 192.168.0.4, 192.168.0.0-192.168.0.31, 192.168.0. * ',
'block_user_popup' => 'Blokir Pengguna',
'block_words_note' => 'Gunakan "*" untuk setiap huruf. Contoh: doh (hanya cocok dengan "doh"), doh * (cocok dengan "doh" atau "dohno"), do * h (cocok dengan "doh", "dooh", "adonan").',
'caching_cleanup' => 'Membersihkan cache',
'caching_delete_all' => 'Hapus seluruh cache',
'caching_delete_complete' => 'Cache berhasil dihapus',
'caching_delete_expired' => 'Hapus cache yang kedaluwarsa',
'caching_delete_progress' => '^1 dari ^2 file cache dihapus ...',
'caching_dir_error' => 'Direktori ^ yang didefinisikan sebagai QA_CACHE_DIRECTORY tidak memiliki hak tulis di server.',
'caching_dir_missing' => 'Direktori cache tidak disetel.',
'caching_dir_public' => 'Direktori ^ yang didefinisikan sebagai QA_CACHE_DIRECTORY harus berada di luar direktori root publik.',
'caching_num_items' => 'Jumlah item dalam cache',
'caching_space_used' => 'Total ukuran cache',
'caching_title' => 'Tembolok',
'cancel_mailing_button' => 'Batalkan pengiriman email',
'categories' => 'Kategori',
'categories_introduction' => 'Klik \' Tambah Kategori \'untuk memulai dengan kategori.',
'categories_not_shown' => 'Beberapa pertanyaan memiliki kategori yang tidak ditampilkan.',
'categories_title' => 'Kategori',
'category_add_sub' => 'Tambahkan sub-kategori',
'category_added' => 'Kategori ditambahkan',
'category_already_used' => 'Ini sudah digunakan oleh sebuah kategori.',
'category_default_slug' => 'Kategori- ^',
'category_description' => 'Deskripsi opsional kategori:',
'category_max_depth_x' => 'Beberapa opsi dapat disembunyikan untuk mencegah kategori lebih dalam dari level ^.',
'category_move_parent' => 'pindah ke elemen induk lain',
'category_name' => 'Nama kategori:',
'category_name_first' => 'Nama kategori pertama:',
'category_no_add_subs_x' => 'Kategori ini tidak dapat memiliki subkategori karena sudah pada level ^.',
'category_no_delete_subs' => 'Kategori ini tidak dapat dihapus karena memiliki subkategori.',
'category_no_sub_error' => '^q Pertanyaan / s dalam kategori ini tidak memiliki subkategori - ^1Tentukan subkategori ^2',
'category_no_sub_to' => 'Pindahkan pertanyaan dalam ^ tanpa subkategori ke:',
'category_no_subs' => 'Tidak ada',
'category_none_error' => '^q pertanyaan / s belum memiliki kategori - ^1 tentukan kategori ^2',
'category_none_to' => 'Pindahkan pertanyaan tanpa kategori ke:',
'category_parent' => 'Kategori induk:',
'category_saved' => 'Kategori disimpan',
'category_slug' => 'Bentuk pendek kategori - fragmen URL:',
'category_subs' => 'Subkategori:',
'category_top_level' => 'Tidak ada kategori induk (tingkat atas)',
'characters' => 'Surat',
'check_language_suffix' => '- ^1periksa file bahasa ^2',
'click_name_edit' => 'Halaman atau tautan sendiri:',
'database_cleanup' => 'Fungsi untuk membersihkan database',
'delete_category' => 'Hapus kategori ini',
'delete_category_reassign' => 'Hapus kategori ini dan tetapkan pertanyaan Anda ke:',
'delete_field' => 'Hapus bidang ini',
'delete_hidden' => 'Hapus entri tersembunyi',
'delete_hidden_complete' => 'Semua entri tersembunyi tanpa ketergantungan telah dihapus',
'delete_hidden_note' => '- semua entri, jawaban, dan komentar tersembunyi tanpa ketergantungan',
'delete_link' => 'Hapus tautan ini',
'delete_page' => 'Hapus halaman ini',
'delete_stop' => 'Batalkan penghapusan',
'delete_title' => 'Hapus judul ini',
'delete_widget_position' => 'Hapus widget ini dari posisi ini',
'edit_custom_page' => 'Edit halaman Anda sendiri',
'edit_field' => '- ^1 edit bidang ^2',
'edit_link' => '- ^1 edit tautan ^2',
'edit_page' => '- ^1Edit halaman ^2',
'edit_title' => '- ^1 edit judul ^2',
'emails_per_minute' => 'Email per menit',
'emails_title' => 'Email',
'enabled' => 'Dirilis',
'feed_link' => 'Umpan',
'feed_link_example' => 'Contoh umpan',
'feeds_title' => 'Umpan RSS',
'field_link_url' => 'URL Tertaut',
'field_multi_line' => 'Beberapa baris teks',
'field_name' => 'Nama bidang:',
'field_single_line' => 'Satu baris teks',
'field_type' => 'Jenis konten:',
'first' => 'pertama',
'flagged_title' => 'Ditandai',
'form_security_expired' => 'Kode keamanan formulir kedaluwarsa - silakan coba lagi',
'from_anon' => 'Dari Anonim:',
'from_users' => 'Dari pengguna:',
'general_title' => 'Umum',
'hidden_answers_deleted' => 'Dihapus: ^1 dari ^2 jawaban tersembunyi tanpa ketergantungan ...',
'hidden_comments_deleted' => 'Dihapus: ^1 dari ^2 komentar tersembunyi ...',
'hidden_questions_deleted' => 'Dihapus: ^1 dari ^2 pertanyaan tersembunyi tanpa ketergantungan ...',
'hidden_title' => 'Tersembunyi',
'hotness_factors' => 'Kepentingan relatif untuk aktualitas pertanyaan:',
'ip_address_pages' => 'halaman alamat IP',
'layout_title' => 'Tata Letak',
'link_name' => 'Teks tautan:',
'link_new_window' => 'Buka tautan di jendela baru',
'link_url' => 'URL tautan - absolut atau relatif terhadap direktori root Q2A:',
'lists_title' => 'Daftar',
'mailing_complete' => 'Email telah terkirim',
'mailing_explanation' => 'Pengguna dapat membatalkan langganan di halaman akun mereka.',
'mailing_progress' => 'Pengiriman email untuk ^1 dari ^2 pengguna selesai ...',
'mailing_title' => 'Pengiriman surat',
'mailing_unsubscribe' => 'Di akhir setiap pesan akan ditambahkan tautan untuk berhenti berlangganan.',
'maintenance_admin_only' => 'Situs web Anda dalam ^1Mode pemeliharaan ^2 dan saat ini tidak dapat diakses oleh pengguna biasa.',
'maximum_x' => '(maksimum ^)',
'memcached_error' => 'Kesalahan memcached: ^',
'moderate_title' => 'Moderasi',
'module_x_database_init' => 'Modul ^1 ^2 membutuhkan ^3 inisialisasi database ^4.',
'most_flagged_title' => 'Konten yang ditandai',
'mysql_version' => 'Versi MySQL:',
'nav_links_explanation' => 'Tampilkan tautan navigasi:',
'nav_qa_is_home' => 'Tanya Jawab (tautan ke halaman beranda)',
'neat_urls_note' => '(memerlukan ^1htaccess ^2) file',
'no_approve_found' => 'Tidak ada konten yang menunggu persetujuan',
'no_classification' => 'Tidak ada',
'no_flagged_found' => 'Konten yang ditandai tidak ditemukan',
'no_hidden_found' => 'Tidak ada konten tersembunyi yang ditemukan',
'no_image_gd' => 'PHP yang terinstal dikompilasi tanpa "GD library". Pengguna tidak dapat mengunggah avatar mereka secara langsung. ',
'no_link' => 'Tidak ada tautan',
'no_memcached' => 'Ekstensi PHP Memcached tidak terpasang.',
'no_multibyte' => 'PHP yang diinstal dikompilasi tanpa dukungan untuk string multibyte. Oleh karena itu, pencarian kurang efektif untuk huruf non-Latin. ',
'no_privileges' => 'Akses ke halaman ini hanya dengan hak administratif.',
'no_unapproved_found' => 'Tidak ada pengguna yang menunggu konfirmasi',
'not_logged_in' => 'Silakan masuk dengan hak administratif ^1 ^2 untuk membuka halaman.',
'opposite_main_menu' => 'Akhir tab di atas',
'options' => 'Pilihan',
'options_reset' => 'Opsi reset',
'options_saved' => 'Opsi disimpan',
'page_already_used' => 'Ini sudah digunakan oleh satu pihak',
'page_content_html' => 'Konten yang akan ditampilkan pada halaman - HTML memungkinkan:',
'page_default_slug' => 'Halaman- ^',
'page_heading' => 'Tajuk yang akan ditampilkan di bagian atas halaman:',
'page_name' => 'Nama halaman (juga untuk tab dan tautan):',
'page_slug' => 'Singkatan halaman (fragmen URL):',
'pages_explanation' => 'Pilih \' Tambah Halaman \'untuk menambahkan konten Anda sendiri ke situs web Q2A Anda, atau \' Tambahkan Tautan \'untuk menautkan ke halaman lain.',
'pages_title' => 'Halaman',
'pause_mailing_button' => 'Tangguhkan pengiriman email',
'per_ip_hour' => 'per IP / jam',
'per_user_hour' => 'per pengguna / jam',
'permissions_title' => 'Izin',
'permit_to_view' => 'Terlihat untuk:',
'php_version' => 'Versi PHP:',
'pixels' => 'Piksel',
'plugin_module' => '(ekstensi: ^)',
'plugin_pages_explanation' => 'Halaman tersedia melalui ekstensi:',
'plugins_title' => 'Ekstensi',
'points' => 'poin',
'points_defaults_shown' => 'Standar ditunjukkan di bawah tetapi BELUM DITERAPKAN:',
'points_required' => 'Jumlah minimum poin untuk mendapatkan gelar:',
'points_title' => 'Poin',
'position' => 'Posisi:',
'posting_title' => 'Post',
'profile_fields' => 'Bidang tambahan pada halaman pengguna atau formulir pendaftaran:',
'q2a_build_date' => 'Tanggal pembuatan:',
'q2a_db_size' => 'Ukuran basis data:',
'q2a_db_version' => 'Versi basis data Q2A:',
'q2a_latest_version' => 'Versi terakhir:',
'q2a_version' => 'Versi Question2Answer:',
'question_lists' => 'Daftar pertanyaan',
'question_pages' => 'Halaman Pertanyaan',
'recalc_categories' => 'Hitung ulang kategori',
'recalc_categories_backpaths' => 'Hitung ulang jalur url untuk kategori ^1 dari ^2 ...',
'recalc_categories_complete' => 'Semua kategori berhasil dihitung ulang.',
'recalc_categories_note' => '- untuk kategori entri dan penghitung kategori',
'recalc_categories_recounting' => 'Perhitungan ulang soal dari kategori ^1 dari ^2 ...',
'recalc_categories_updated' => 'Perhitungan ulang entri ^1 dari ^2 ...',
'recalc_hotness_q_view_note' => 'Dapat membuat halaman dimuat lebih cepat jika dimatikan. Namun, nilai panas tidak akan diperbarui jika panggilan diperhitungkan dalam pengaturan panas.',
'recalc_points' =>' Perhitungan ulang nilai poin pengguna',
'recalc_points_complete' => 'Nilai poin pengguna berhasil dihitung ulang.',
'recalc_points_note' => '- untuk menampilkan peringkat dan poin pengguna',
'recalc_points_recalced' => 'Perhitungan ulang untuk pengguna ^1 dari ^2 ...',
'recalc_points_usercount' => 'Perkirakan jumlah total pengguna ...',
'recalc_posts_count' => 'Dapatkan jumlah pertanyaan, jawaban, dan komentar ...',
'recalc_stop' => 'Hentikan penghitungan ulang',
'recent_approve_title' => 'Konten baru menunggu persetujuan',
'recent_hidden_title' => 'Konten yang baru saja disembunyikan',
'recount_posts' => 'Hitung entri lagi',
'tags' => "Tags",
'recount_posts_as_recounted' => 'Balasan dan popularitas yang baru dihitung untuk entri ^1 dari ^2 ...',
'recount_posts_complete' => 'Semua entri berhasil dihitung ulang.',
'recount_posts_note' => '- Jumlah balasan, peringkat, tanda dan popularitas untuk setiap posting',
'recount_posts_stop' => 'Hentikan penghitungan ulang',
'recount_posts_votes_recounted' => 'Suara dan tanda yang baru dihitung untuk entri ^1 dari ^2 ...',
'refill_events' => 'Isi ulang aliran acara',
'refill_events_complete' => 'Semua aliran acara akan diisi ulang.',
'refill_events_note' => '- untuk daftar pembaruan setiap pengguna',
'refill_events_refilled' => 'Isi ulang untuk pertanyaan ^1 dari ^2 ...',
'registration_fields' => 'tambah bidang untuk pendaftaran',
'reindex_content' => 'Indeks ulang konten',
'reindex_content_note' => '- untuk mencari dan menyarankan pertanyaan terkait',
'reindex_content_stop' => 'Hentikan pengindeksan ulang',
'reindex_pages_reindexed' => 'Halaman indeks ^1 dari ^2 ...',
'reindex_posts_complete' => 'Semua entri berhasil diindeks ulang.',
'reindex_posts_reindexed' => 'Indeks entri ^1 dari ^2 ...',
'reindex_posts_wordcounted' => 'Kata-kata ^1 dari ^2 diceritakan ...',
'requires_php_version' => 'Nonaktif - membutuhkan PHP ^ atau lebih tinggi',
'requires_q2a_version' => 'Dinonaktifkan - membutuhkan Question2Answer ^ atau lebih tinggi',
'reset_options_button' => 'Setel ulang ke nilai default',
'reset_options_confirm' => 'Apakah Anda yakin ingin semua pengaturan pada halaman ini diatur ulang ke nilai default?',
'resume_mailing_button' => 'Lanjutkan mengirim email',
'save_options_button' => 'Simpan pengaturan',
'save_recalc_button' => 'Simpan dan hitung ulang',
'save_view_button' => 'Simpan dan lihat',
'send_test_button' => 'Kirim ke saya untuk tes',
'show_defaults_button' => 'Tampilkan pengaturan default',
'show_on_register_form' => 'Tampilkan kolom dalam formulir pendaftaran',
'slug_bad_chars' => 'Bentuk singkat tidak boleh berisi karakter berikut: ^',
'slug_reserved' => 'Formulir singkat ini disediakan untuk halaman lain',
'spam_title' => 'Spam',
'start_mailing_button' => 'Mulai mengirim email',
'stats_title' => 'Statistik',
'stop_recalc_warning' => 'Database sedang dibersihkan. Proses akan terganggu jika Anda menutup jendela sekarang. ',
'tag_pages' => 'Tag Halaman',
'tags_and_categories' => 'Tag dan kategori',
'tags_not_shown' => 'Beberapa pertanyaan memiliki tag yang tidak ditampilkan.',
'test_sent_to_x' => 'Pesan percobaan telah dikirim ke ^',
'title_already_used' => 'Nilai ini sudah digunakan oleh judul lain',
'top_level_categories' => 'Kategori tingkat teratas:',
'total_as' => 'Jumlah jawaban:',
'total_cs' => 'Jumlah komentar:',
'total_qs' => 'Jumlah pertanyaan:',
'total_qs_unans' => 'Jumlah pertanyaan yang belum terjawab:',
'unnamed_plugin' => 'Plugin tanpa judul',
'upgrade_db' => 'Database Question2Answer Anda perlu ditingkatkan ^1 untuk versi ini ^2.',
'url_format_note' => 'Opsi dengan label ^ dapat diatur di situs web Anda. Untuk pengoptimalan mesin pencari (SEO) terbaik, gunakan opsi ^ pertama yang tersedia. ',
'user_pages' => 'Halaman Pengguna',
'user_title' => 'Judul pengguna - HTML mungkin:',
'user_titles' => 'Judul pengguna berdasarkan poin:',
'users_active' => 'Pengguna aktif:',
'users_must_have' => 'Pengguna harus memiliki',
'users_posted' => 'Pengguna yang telah memposting:',
'users_registered' => 'Pengguna terdaftar:',
'users_title' => 'Pengguna',
'users_voted' => 'Pengguna yang memilih:',
'version_get_x' => 'dapatkan ^',
'version_latest' => 'terakhir',
'version_latest_unknown' => 'terakhir tidak diketahui',
'version_requires_php' => '^1 membutuhkan PHP ^2',
'version_requires_q2a' => '^1 membutuhkan Q2A ^2',
'viewing_title' => 'Lihat',
'widget_all_pages' => 'Tampilkan widget saat ini di semua halaman yang tersedia.',
'widget_global_options' => '- ^1Opsi ^2',
'widget_name' => 'Nama widget:',
'widget_no_positions' => 'Widget ini telah ditambahkan ke setiap posisi yang tersedia.',
'widget_not_available' => 'Widget ini tidak tersedia. Mungkin plugin yang menyediakan widget tidak lagi terpasang. ',
'widget_pages_explanation' => 'Tampilkan widget saat ini di halaman berikut:',
'widgets_explanation' => 'Widget yang tersedia:',
);

/*
 	 Omit PHP closing tag to help avoid accidental output
*/
