<?php
/*
        Question2Answer by Gideon Greenspan and contributors
        http://www.question2answer.org/

        File: qa-lang/de/qa-lang-options.php
        Version: 1.8
        Date: 2019-12-26
        Description: Language phrases for all options, as shown in admin center
                     in formal German (Sie)
        Translation: Fulgor@github

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array('allow_anonymous_naming' => 'Izinkan pengguna anonim untuk memasukkan nama mereka saat memposting:',
'allow_change_usernames' => 'Izinkan pengguna dengan pos untuk mengubah nama pengguna mereka:',
'allow_close_questions' => 'Pertanyaan dapat ditutup secara manual:',
'allow_close_own_questions' => 'Izinkan pengguna untuk menutup pertanyaan mereka sendiri:',
'allow_login_email_only' => 'Hanya masuk dengan alamat email (bukan dengan nama pengguna):',
'allow_multi_answers' => 'Izinkan beberapa jawaban per pengguna:',
'allow_no_category' => 'Izinkan pertanyaan tanpa kategori',
'allow_no_sub_category' => 'Izinkan pertanyaan dengan kategori tetapi tanpa subkategori',
'allow_private_messages' => 'Izinkan pesan pribadi antar pengguna:',
'allow_self_answer' => 'Izinkan pengguna menjawab pertanyaan mereka sendiri:',
'allow_user_walls' => 'Aktifkan kiriman dinding di profil pengguna:',
'allow_view_q_bots' => 'Izinkan mesin pencari menampilkan halaman pertanyaan',
'approve_user_required' => 'Semua pengguna baru harus dikonfirmasi:', // @deprecated
'avatar_allow_gravatar' => 'Izinkan avatar dari ^1Gravatar ^2:',
'avatar_allow_upload' => 'Izinkan pengguna mengunggah avatar:',
'avatar_default_show' => 'Avatar bawaan:',
'avatar_message_list_size' => 'Ukuran avatar dalam daftar pesan:',
'avatar_profile_size' => 'Ukuran avatar di profil pengguna:',
'avatar_q_list_size' => 'Ukuran avatar dalam daftar pertanyaan:',
'avatar_q_page_a_size' => 'Ukuran avatar untuk balasan:',
'avatar_q_page_c_size' => 'Ukuran avatar untuk komentar:',
'avatar_q_page_q_size' => 'Ukuran avatar untuk pertanyaan:',
'avatar_store_size' => 'Ukuran file maksimum untuk avatar:',
'avatar_users_size' => 'Ukuran avatar di sisi pengguna teratas:',
'block_bad_usernames' => 'Nama pengguna terlarang - dipisahkan dengan spasi atau koma:',
'block_bad_words' => 'Kata-kata yang disensor - dipisahkan dengan spasi atau koma:',
'block_ips_write' => 'Alamat IP yang diblokir - dipisahkan dengan spasi atau koma:',
'caching_catwidget_time' => 'Widget kategori cache untuk:',
'caching_enabled' => 'Aktifkan cache:',
'caching_driver' => 'Pengandar caching',
'caching_filesystem' => 'Sistem file',
'caching_memcached' => 'Memcached',
'caching_q_start' => 'Mulai pertanyaan caching setelah:',
'caching_q_time' => 'Cache halaman pertanyaan untuk:',
'caching_qlist_time' => 'Cache daftar pertanyaan untuk:',
'captcha_module' => 'Gunakan modul captcha:',
'captcha_on_anon_post' => 'Gunakan captcha untuk kiriman anonim:',
'captcha_on_feedback' => 'Gunakan captcha dalam formulir umpan balik:',
'captcha_on_register' => 'Gunakan captcha untuk pendaftaran pengguna:',
'captcha_on_reset_password' => 'Gunakan captcha dalam formulir untuk mereset kata sandi:',
'captcha_on_unapproved' => 'Gunakan captcha jika pengguna belum disetujui:',
'captcha_on_unconfirmed' => 'Gunakan captcha jika email belum terkonfirmasi:',
'columns_tags' => 'Kolom pada halaman kata kunci:',
'columns_users' => 'Kolom di sisi pengguna:',
'comment_on_as' => 'Izinkan komentar pada balasan:',
'comment_on_qs' => 'Izinkan komentar pada pertanyaan:',
'confirm_user_emails' => 'Menunggu konfirmasi email pengguna:',
'confirm_user_required' => 'Semua pengguna baru harus mengkonfirmasi email mereka:',
'custom_home_content' => 'Konten beranda - HTML diizinkan:',
'custom_home_heading' => 'Judul beranda:',
'default_privacy' => 'Perlindungan data: Alamat email Anda tidak akan diteruskan atau dijual kepada pihak ketiga.',
'default_sidebar' => 'Selamat datang di ^ tempat Anda dapat mengajukan pertanyaan dan mendapatkan jawaban dari anggota komunitas lainnya.',
'default_subject' => 'Pesan dari ^',
'default_suffix' => 'Tanya Jawab',
'default_terms' => 'Saya setuju dengan ^ Syarat dan Ketentuan Umum dan Kebijakan Privasi.',
'do_ask_check_qs' => 'Cari pertanyaan serupa saat Anda bertanya:',
'do_close_on_select' => 'Tutup pertanyaan dengan jawaban yang dipilih:',
'do_complete_tags' => 'Tampilkan kata kunci yang cocok saat Anda mengetik:',
'do_count_q_views' => 'Hitung jumlah panggilan pertanyaan:',
'do_example_tags' => 'Tampilkan contoh tag berdasarkan pertanyaan:',
'editor_for_as' => 'Editor standar untuk tanggapan:',
'editor_for_cs' => 'Editor standar untuk komentar:',
'editor_for_qs' => 'Editor standar untuk pertanyaan:',
'email_privacy' => 'Kebijakan privasi untuk alamat email - HTML memungkinkan:',
'extra_field_active' => 'Bidang pengguna untuk informasi tambahan pada formulir permintaan:',
'extra_field_display' => 'Menampilkan informasi tambahan pada halaman pertanyaan',
'extra_field_display_label' => 'Menampilkan informasi tambahan pada halaman pertanyaan dengan label:',
'feed_for_activity' => 'Umpan untuk aktivitas terkini:',
'feed_for_hot' => 'Umpan untuk pertanyaan yang sedang tren:',
'feed_for_qa' => 'Umpan untuk pertanyaan dan jawaban saat ini:',
'feed_for_questions' => 'Umpan untuk pertanyaan saat ini:',
'feed_for_search' => 'Umpan untuk hasil pencarian:',
'feed_for_tag_qs' => 'Umpan untuk pertanyaan tentang setiap tag:',
'feed_for_unanswered' => 'Umpan untuk pertanyaan yang belum terjawab:',
'feed_full_text' => 'Sertakan teks lengkap dalam umpan:',
'feed_number_items' => 'Panjang maksimum feed:',
'feed_per_category' => 'Umpan individu per kategori:',
'feedback_email' => 'Alamat email untuk pesan admin - tidak akan ditampilkan kepada pengguna:',
'feedback_enabled' => 'Sediakan halaman di mana pengguna dapat mengirim umpan balik',
'flagging_hide_after' => 'Secara otomatis menyembunyikan postingan yang mencapai:',
'flagging_notify_every' => 'Email saya setelah setiap tambahan:',
'flagging_notify_first' => 'Email saya saat ada kiriman:',
'flagging_of_posts' => 'Izinkan kiriman ditandai:',
'follow_on_as' => 'Pertanyaan mungkin terkait dengan jawaban:',
'from_email' => 'Dari alamat untuk pesan dari situs:',
'hot_weight_a_age' => 'Pertanyaan memiliki jawaban baru:',
'hot_weight_answers' => 'Pertanyaan memiliki banyak jawaban baru:',
'hot_weight_q_age' => 'Pertanyaan baru:',
'hot_weight_views' => 'Pertanyaan sering dilihat:',
'hot_weight_votes' => 'Pertanyaan memiliki banyak suara positif:',
'links_in_new_window' => 'Buka URL tertaut di jendela baru:',
'logo_height' => 'Tinggi logo:',
'logo_show' => 'Tampilkan gambar logo di header halaman',
'logo_url' => 'URL logo - absolut atau relatif terhadap akar Q2A:',
'logo_width' => 'Lebar logo:',
'mailing_body' => 'Teks isi:',
'mailing_enabled' => 'Aktifkan pengiriman surat massal untuk semua pengguna',
'mailing_from_email' => 'Dari alamat email:',
'mailing_from_name' => 'Dari Nama:',
'mailing_per_minute' => 'Tarif pengiriman surat maksimum:',
'mailing_subject' => 'Baris subjek:',
'match_1' => 'Tersempit',
'match_2' => 'Sempit',
'match_3' => 'Standar',
'match_4' => 'Lebih lebar',
'match_5' => 'Terluas',
'match_ask_check_qs' => 'Pertanyaan serupa yang cocok:',
'match_example_tags' => 'Contoh tag yang cocok:',
'match_related_qs' => 'Pertanyaan terkait yang cocok:',
'max_len_q_title' => 'Panjang maksimum judul pertanyaan:',
'max_num_q_tags' => 'Jumlah tag maksimum:',
'max_rate_ip_as' => 'Batas nilai untuk menambahkan jawaban:',
'max_rate_ip_cs' => 'Batas penilaian untuk publikasi komentar:',
'max_rate_ip_flags' => 'Batas nilai untuk posting yang ditandai:',
'max_rate_ip_logins' => 'Batas nilai untuk login:',
'max_rate_ip_messages' => 'Batas nilai untuk pesan pribadi dan pesan dinding:',
'max_rate_ip_qs' => 'Batas penilaian untuk pertanyaan:',
'max_rate_ip_registers' => 'Batas peringkat untuk pendaftaran pengguna:',
'max_rate_ip_uploads' => 'Batas peringkat untuk mengunggah file:',
'max_rate_ip_votes' => 'Batas peringkat untuk peringkat:',
'max_rate_user_as' => 'Respons maksimum per pengguna dan jam:',
'max_rate_user_cs' => 'Komentar maksimum per pengguna dan jam:',
'max_rate_user_flags' => 'Bendera maksimum per pengguna dan jam:',
'max_rate_user_messages' => 'Pesan pribadi maksimum per pengguna dan jam:',
'max_rate_user_qs' => 'Pertanyaan maksimum per pengguna dan jam:',
'max_rate_user_uploads' => 'Unggahan maksimum per pengguna dan jam:',
'max_rate_user_votes' => 'Suara maksimum per pengguna dan jam:',
'min_len_a_content' => 'Panjang respons minimum:',
'min_len_c_content' => 'Panjang minimum komentar:',
'min_len_q_content' => 'Panjang minimum komentar pada pertanyaan:',
'min_len_q_title' => 'Panjang minimal judul pertanyaan:',
'min_num_q_tags' => 'Jumlah minimum kata kunci:',
'minify_html' => 'Perkecil HTML:',
'moderate_anon_post' => 'Sedang posting anonim:',
'moderate_by_points' => 'Sedang pengguna dengan sedikit poin:',
'moderate_edited_again' => 'Moderasi posting lagi setelah perubahan:',
'moderate_notify_admin' => 'Email saya jika ada postingan yang perlu dimoderasi:',
'moderate_points_limit' => 'Sedang untuk pengguna dengan kurang dari:',
'moderate_unapproved' => 'Sedang untuk pengguna yang belum disetujui:',
'moderate_unconfirmed' => 'Sedang untuk pengguna tanpa konfirmasi email:',
'moderate_update_time' => 'Waktu untuk menampilkan postingan yang dimoderasi:',
'moderate_users' => 'Aktifkan moderasi (persetujuan) untuk pengguna:',
'neat_urls' => 'Struktur URL:',
'notify_admin_q_post' => 'Kirim alamat ini melalui email jika ada pertanyaan',
'notify_users_default' => 'Aktifkan bidang pemberitahuan email secara default:',
'option_default' => 'Standar',
'page_size_activity' => 'Panjang halaman semua aktivitas:',
'page_size_ask_check_qs' => 'Jumlah maksimum pertanyaan serupa yang dapat ditampilkan:',
'page_size_ask_tags' => 'Jumlah maksimum tip kata kunci yang dapat ditampilkan:',
'page_size_home' => 'Panjang halaman Tanya Jawab:',
'page_size_hot_qs' => 'Panjang halaman panas:',
'page_size_pms' => 'Pesan pribadi per halaman:',
'page_size_q_as' => 'Jumlah jawaban maksimum per halaman:',
'page_size_qs' => 'Panjang halaman pertanyaan:',
'page_size_related_qs' => 'Jumlah maksimum pertanyaan terkait:',
'page_size_search' => 'Hasil pencarian per halaman:',
'page_size_tag_qs' => 'Pertanyaan tentang setiap halaman tag:',
'page_size_tags' => 'Panjang halaman tag:',
'page_size_una_qs' => 'Panjang halaman "belum terjawab":',
'page_size_users' => 'Panjang halaman pengguna:',
'page_size_wall' => 'Entri dinding per halaman:',
'pages_prev_next' => 'Tautan ke halaman sebelumnya/berikutnya:',
'permit_admins' => 'Administrator',
'permit_all' => 'Semuanya',
'permit_approve_users' => 'Setujui pengguna terdaftar:',
'permit_approved' => 'Hanya pengguna terdaftar',
'permit_approved_points' => 'Pengguna terdaftar dengan poin yang cukup',
'permit_block' => 'Blokir atau buka blokir pengguna atau IP:',
'permit_confirmed' => 'Pengguna terdaftar dengan email yang dikonfirmasi',
'permit_create_admins' => 'Buat administrator:',
'permit_create_eds_mods' => 'Buat editor dan moderator:',
'permit_create_experts' => 'Buat pakar:',
'permit_delete_users' => 'Hapus pengguna:',
'permit_editors' => 'Editor, moderator, administrator',
'permit_experts' => 'Pakar, editor, moderator, administrator',
'permit_moderators' => 'Moderator dan Administrator',
'permit_points' => 'Pengguna terdaftar dengan poin yang cukup',
'permit_points_confirmed' => 'Terdaftar & email dikonfirmasi & poin cukup',
'permit_see_emails' => 'Tampilkan alamat email pengguna:',
'permit_supers' => 'Administrator Super',
'permit_users' => 'Pengguna terdaftar',
'place_full_below_content' => 'Lebar penuh - di bawah konten',
'place_full_below_footer' => 'Lebar penuh - di bawah footer',
'place_full_below_nav' => 'Lebar penuh - di bawah navigasi',
'place_full_top' => 'Lebar penuh - di bagian atas halaman',

'place_main_below_lists' => 'Area utama - Daftar di bawah',
'place_main_below_title' => 'Area utama - Di bawah judul',
'place_main_bottom' => 'Area utama - Bawah',
'place_main_top' => 'Area utama - Atas',
'place_side_below_categories' => 'Panel samping - Di bawah kategori', // @deprecated
'place_side_below_sidebar' => 'Panel samping - Di bawah kotak bilah sisi',
'place_side_low' => 'Panel samping - Rendah',
'place_side_last' => 'Panel samping - Terakhir',
'place_side_top' => 'Panel samping - Atas',
'points_a_selected' => 'Memilih jawaban Anda sebagai yang terbaik:',
'points_a_voted_max_gain' => 'Batasi dari up vote untuk setiap jawaban:',
'points_a_voted_max_loss' => 'Batasi suara dari bawah untuk setiap jawaban:',
'points_base' => 'Tambahkan untuk semua pengguna:',
'points_c_voted_max_gain' => 'Batasi dari up vote pada setiap komentar:',
'points_c_voted_max_loss' => 'Batasi dari bawah suara pada setiap komentar:',
'points_multiple' => 'Kalikan semua poin:',
'points_per_a_voted_down' => 'Jawaban Anda tidak setuju:',
'points_per_a_voted_up' => 'Pilihan terbaik untuk jawaban Anda:',
'points_per_c_voted_down' => 'Berkurangnya suara pada komentar Anda:',
'points_per_c_voted_up' => 'Pilihan terbaik untuk komentar Anda:',
'points_per_q_voted_down' => 'Permintaan suara rendah untuk pertanyaan Anda:',
'points_per_q_voted_up' => 'Pilihan maksimal untuk pertanyaan Anda:',
'points_post_a' => 'Memposting jawaban:',
'points_post_q' => 'Memposting pertanyaan:',
'points_q_voted_max_gain' => 'Batasi dari suara terbanyak untuk setiap pertanyaan:',
'points_q_voted_max_loss' => 'Batasi suara dari bawah untuk setiap pertanyaan:',
'points_select_a' => 'Memilih jawaban untuk pertanyaan Anda:',
'points_vote_down_a' => 'Memilih jawaban:',
'points_vote_down_q' => 'Mengisi pertanyaan:',
'points_vote_up_a' => 'Memilih jawaban:',
'points_vote_up_q' => 'Memilih pertanyaan:',
'q_urls_remove_accents' => 'Hapus aksen dari URL pertanyaan:',
'q_urls_title_length' => 'Panjang judul pertanyaan di URL:',
'recalc_hotness_q_view' => 'Hitung ulang hotness pada setiap tampilan halaman pertanyaan:',
'register_notify_admin' => 'Email saya ketika pengguna baru mendaftar:',
'search_module' => 'Gunakan modul pencarian:',
'show_a_form_immediate' => 'Tampilkan formulir jawaban segera:',
'show_always' => 'Selalu',
'show_c_reply_buttons' => 'Tampilkan tombol balas di komentar:',
'show_compact_numbers' => 'Tampilkan bilangan kompak (mis. 1.3k):',
'show_custom_answer' => 'Pesan khusus pada formulir jawaban - HTML diizinkan:',
'show_custom_ask' => 'Pesan khusus pada formulir permintaan - HTML diizinkan:',
'show_custom_comment' => 'Pesan khusus pada formulir komentar - HTML diizinkan:',
'show_custom_footer' => 'HTML Khusus di bagian bawah setiap halaman:',
'show_custom_header' => 'HTML khusus di bagian atas setiap halaman:',
'show_custom_home' => 'Konten khusus di halaman beranda alih-alih Tanya Jawab',
'show_custom_in_head' => 'HTML khusus di bagian <head> setiap halaman:',
'show_custom_register' => 'Pesan khusus pada formulir pendaftaran - HTML diizinkan:',
'show_custom_sidebar' => 'HTML Kustom di kotak sidebar di setiap halaman:',
'show_custom_sidepanel' => 'HTML khusus di panel samping di setiap halaman:',
'show_custom_welcome' => 'Pesan khusus dalam email yang dikirim ke pengguna baru yang terdaftar:',
'show_fewer_cs_count' => 'Jika sebagian tersembunyi, tampilkan yang terbaru:',
'show_fewer_cs_from' => 'Sembunyikan sebagian komentar jika lebih dari:',
'show_full_date_days' => 'Tampilkan tanggal lengkap setelah:',
'show_home_description' => 'Sertakan deskripsi <meta> untuk halaman beranda:',
'show_if_no_as' => 'Jika tidak ada jawaban',
'show_message_history' => 'Menyimpan dan menampilkan riwayat pesan pribadi:',
'show_never' => 'Tidak pernah',
'show_notice_visitor' => 'Pemberitahuan di atas untuk pengunjung pertama kali - HTML diizinkan:',
'show_notice_welcome' => 'Pemberitahuan di atas untuk pengguna baru yang terdaftar - HTML diizinkan:',
'show_post_update_meta' => 'Tampilkan suntingan/pembaruan di meta pos:',
'show_register_terms' => 'Syarat & Ketentuan kotak centang pada formulir pendaftaran - HTML diperbolehkan:',
'show_selected_first' => 'Pindahkan jawaban yang dipilih ke atas:',
'show_url_links' => 'Deteksi dan tautkan URL di postingan:',
'show_user_points' => 'Tampilkan poin di sebelah nama pengguna:',
'show_user_titles' => 'Tampilkan judul di sebelah nama pengguna:',
'show_view_count_q_page' => 'Tampilkan jumlah penayangan pada halaman pertanyaan:',
'show_view_counts' => 'Tampilkan jumlah tampilan dalam daftar pertanyaan:',
'show_when_created' => 'Tampilkan usia posting pengguna:',
'site_language' => 'Bahasa situs:',
'site_maintenance' => 'Hapus situs untuk pemeliharaan sementara',
'site_text_direction' => 'Arah teks situs:',
'site_theme' => 'Tema situs:',
'site_theme_mobile' => 'Tema untuk ponsel:',
'site_title' => 'Tanya Jawab Nama Situs:',
'site_url' => 'URL situs pilihan:',
'smtp_active' => 'Kirim email melalui SMTP, bukan email lokal',
'smtp_address' => 'Alamat server SMTP:',
'smtp_authenticate' => 'Kirim nama pengguna dan kata sandi SMTP',
'smtp_password' => 'Kata sandi SMTP:',
'smtp_port' => 'Port server SMTP:',
'smtp_secure' => 'Koneksi SMTP aman:',
'smtp_secure_none' => 'Tidak ada',
'smtp_username' => 'Nama pengguna SMTP:',
'sort_answers_by' => 'Urutkan jawaban menurut:',
'sort_time' => 'Waktu',
'sort_votes' => 'Suara',
'suspend_register_users' => 'Tangguhkan sementara pendaftaran pengguna baru:',
'tag_separator_comma' => 'Gunakan koma sebagai satu-satunya pemisah tag:',
'tags_or_categories' => 'Klasifikasi pertanyaan:',
'time_approved' => 'Waktu disetujui',
'time_written' => 'Waktu ditulis',
'use_microdata' => 'Gunakan microdata schema.org:',
'votes_separated' => 'Tampilkan suara naik dan turun yang terpisah:',
'voting_on_as' => 'Izinkan pemungutan suara pada jawaban:',
'voting_on_cs' => 'Izinkan pemungutan suara pada komentar:',
'voting_on_q_page_only' => 'Izinkan pemungutan suara hanya pada halaman pertanyaan:',
'voting_on_qs' => 'Izinkan pemungutan suara untuk pertanyaan:',
);

/*
 	 Omit PHP closing tag to help avoid accidental output
*/
