<?php

/*

    Question2Answer by Gideon Greenspan and contributors
    http://www.question2answer.org/

    File: qa-lang/de/qa-lang-question.php
    Version: 1.8
    Date: 2019-09-19
    Description: Language phrases for question page in German
    Translation: Peter Chiochetti, Moritz Bunkus, Philip Schilling, Corinna Baldauf, Fulgor@github

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    More about this license: http://www.question2answer.org/license.php
    
    ATTENTION: Don't change '1' in translation of >1_answer_title' => '1 Answer',<
    to a string e.g. 'Eine ". This creates an error when displaying the very first entry.
*/

    return array(        '1_answer_title' => '1 jawaban',
        'a_convert_to_c' => 'Beri komentar dari jawaban ini',
        'a_convert_to_c_on' => 'Berikan komentar dari jawaban ini di:',
        'a_convert_warn' => 'Peringatan: Tindakan ini tidak dapat dibatalkan.',
        'a_convert_warn_cs' => 'Peringatan: Tindakan ini tidak dapat dibatalkan dan juga akan memindahkan komentar dari jawaban.',
        'a_notify_email' => 'Saya ingin menerima email ke alamat berikut jika jawaban saya dipilih atau dikomentari:',
        'a_notify_label' => 'Saya ingin menerima email jika jawaban saya dipilih atau dikomentari',
        'a_notify_x_label' => 'Saya ingin menerima email (^), jika jawaban saya dipilih atau dikomentari',
        'a_waiting_your_approval' => 'Jawaban ini menunggu persetujuan Anda',
        'a_your_waiting_approval' => 'Pertanyaan Anda akan segera ditinjau dan kemudian disetujui.',
        'add_answer_button' => 'Kirim Jawaban',
        'add_comment_button' => 'Komentari',
        'add_q_favorites' => 'Tambahkan pertanyaan ini ke favorit saya',
        'anon_name_label' => 'Nama Anda yang akan ditampilkan (opsional):',
        'answer_button' => 'Jawab',
        'answer_limit' => 'Menerima terlalu banyak jawaban - coba lagi dalam satu jam',
        'answer_must_be_approved' => 'Akun Anda harus disetujui sebelum Anda dapat menjawab pertanyaan apa pun. Harap tunggu atau ^1 tambahkan informasi lebih lanjut ^2. ',
        'answer_must_confirm' => 'Harap ^5 konfirmasi alamat email Anda ^6 untuk menjawab pertanyaan.',
        'answer_must_login' => 'Silahkan ^1 login ^2 atau ^3 daftar ^4 untuk menjawab pertanyaan.',
        'answer_q_popup' => 'Jawab pertanyaan ini',
        'approve_a_popup' => 'Setujui tanggapan ini',
        'approve_button' => 'setujui',
        'approve_c_popup' => 'Setujui komentar ini',
        'approve_q_popup' => 'Setujui pertanyaan ini',
        'ask_button' => 'Ajukan pertanyaan',
        'ask_follow_from_a' => 'Pertanyaan Anda mirip dengan jawaban berikut:',
        'ask_follow_title' => 'Ajukan pertanyaan serupa',
        'ask_limit' => 'Menerima terlalu banyak pertanyaan - coba lagi dalam satu jam',
        'ask_must_be_approved' => 'Akun Anda harus disetujui sebelum Anda dapat mengajukan pertanyaan. Harap tunggu atau ^1 tambahkan informasi lebih lanjut ^2. ',
        'ask_must_confirm' => 'Harap ^5 konfirmasi alamat email Anda ^6 untuk mengajukan pertanyaan.',
        'ask_must_login' => 'Silakan ^1 login ^2 atau ^3 daftar ^4 untuk mengajukan pertanyaan.',
        'ask_same_q' => 'Silakan lihat apakah pertanyaan Anda sudah ditanyakan sebelum melanjutkan:',
        'ask_title' => 'Ajukan pertanyaan',
        'c_notify_email' => 'Saya ingin menerima email ke alamat berikut jika seseorang berkomentar setelah saya:',
        'c_notify_label' => 'Saya ingin menerima email jika seseorang berkomentar setelah saya',
        'c_notify_x_label' => 'Saya ingin menerima email (^) jika seseorang berkomentar setelah saya',
        'c_waiting_your_approval' => 'Komentar ini menunggu untuk disetujui',
        'c_your_waiting_approval' => 'Komentar Anda akan segera ditinjau dan kemudian disetujui.',
        'category_ask_not_allowed' => 'Anda tidak diperbolehkan mengajukan pertanyaan dalam kategori ini.',
        'category_js_note' => 'Untuk memilih kategori, silakan aktifkan Javascript di browser Anda.',
        'category_required' => 'Silakan pilih kategori',
        'claim_a_popup' => 'Tetapkan jawaban ini ke akun Anda sendiri',
        'claim_button' => 'Saya yang menulisnya',
        'claim_c_popup' => 'Tetapkan komentar ini ke akun Anda sendiri',
        'claim_q_popup' => 'Tetapkan pertanyaan ini ke akun Anda sendiri',
        'clear_flags_button' => 'Hapus laporan spam',
        'clear_flags_popup' => 'Hapus pesan spam dari semua pengguna',
        'close_button' => 'tutup',
        'close_duplicate' => 'Ini adalah duplikat dari pertanyaan lain',
        'close_duplicate_error' => 'Duplikat pertanyaan tidak dapat ditemukan - coba masukkan nomor URL untuk pertanyaan lain, misalnya 123.',
        'close_form_button' => 'Tutup pertanyaan',
        'close_form_title' => 'Tutup pertanyaan ini',
        'close_original_note' => 'Anda juga dapat memasukkan nomor dari URL pertanyaan lain, misalnya 123.',
        'close_original_title' => 'URL dari pertanyaan awal:',
        'close_q_popup' => 'Tutup pertanyaan ini untuk jawaban baru',
        'close_reason_title' => 'Penutupan Alasan:',
        'closed_as_duplicate' => 'ditutup sebagai duplikat dari:',
        'closed_with_note' => 'ditutup dengan komentar:',
        'comment_a_popup' => 'Komentar jawaban ini',
        'comment_button' => 'Komentar',
        'comment_limit' => 'Terlalu banyak komentar yang diterima - silakan coba lagi dalam satu jam',
        'comment_must_be_approved' => 'Akun Anda harus disetujui sebelum Anda dapat berkomentar. Harap tunggu atau ^1 tambahkan informasi lebih lanjut ^2. ',
        'comment_must_confirm' => 'Harap ^5 konfirmasi alamat email Anda ^6 untuk berkomentar.',
        'comment_must_login' => 'Silakan ^1login ^2 atau ^3daftar ^4 untuk berkomentar.',
        'comment_on_a' => 'Jawabannya:',
        'comment_on_q' => 'Untuk pertanyaan:',
        'comment_q_popup' => 'Komentar pertanyaan ini',
        'delete_a_popup' => 'Hapus jawaban ini secara permanen',
        'delete_button' => 'Hapus',
        'delete_c_popup' => 'Hapus komentar ini secara permanen',
        'delete_q_popup' => 'Hapus pertanyaan ini secara permanen',
        'duplicate_content' => 'Pos Anda sepertinya duplikat.',
        'edit_a_popup' => 'Edit jawaban ini',
        'edit_a_title' => 'Edit jawaban',
        'edit_button' => 'Edit',
        'edit_c_popup' => 'Edit komentar ini',
        'edit_c_title' => 'Edit komentar',
        'edit_must_confirm' => 'Harap ^5konfirmasi alamat email Anda ^6 untuk mengedit ini.',
        'edit_must_login' => 'Silakan ^1 login ^2 atau ^3 daftar ^4 untuk mengedit ini.',
        'edit_q_popup' => 'Sunting pertanyaan ini',
        'edit_q_title' => 'Sunting pertanyaan',
        'example_tags' => 'Contoh Tanda:',
        'flag_a_popup' => 'Laporkan tanggapan ini sebagai spam atau tak pantas',
        'flag_button' => 'Laporkan SPAM',
        'flag_c_popup' => 'Tandai komentar ini sebagai spam atau tidak pantas',
        'flag_hide_button' => 'Laporkan dan sembunyikan spam',
        'flag_limit' => 'Anda terlalu banyak posting - coba lagi dalam satu jam',
        'flag_must_confirm' => 'Harap ^5 konfirmasi alamat email Anda ^6 agar Anda dapat menandai kiriman.',
        'flag_must_login' => 'Silakan ^1 login ^2 atau ^3 daftar ^4 untuk dapat menandai posting.',
        'flag_not_allowed' => 'Tidak diperbolehkan melaporkan ini sebagai spam',
        'flag_q_popup' => 'Tandai pertanyaan ini sebagai spam atau tidak pantas',
        'follow_a_popup' => 'Ajukan pertanyaan baru terkait jawaban ini',
        'follow_button' => 'Ajukan pertanyaan tentang ini',
        'follows_a' => 'mengacu pada jawaban untuk:',
        'follows_q' => 'tentang pertanyaan ini:',
        'hide_a_popup' => 'Sembunyikan jawaban ini',
        'hide_button' => 'Sembunyikan',
        'hide_c_popup' => 'Sembunyikan komentar ini',
        'hide_q_popup' => 'Sembunyikan pertanyaan ini',
        'matching_tags' => 'Tag ditemukan:',
        'max_tags_x' => 'Maksimum tag ^ diperbolehkan',
        'min_tags_x' => 'Masukkan minimal ^ hari / s',
        'notify_email_note' => 'Pemberitahuan perlindungan data: Alamat email Anda hanya akan digunakan untuk mengirimkan pemberitahuan kepada Anda. Kebijakan privasi berlaku. ',
        'q_category_label' => 'Kategori:',
        'q_content_label' => 'Pertanyaan Anda secara detail:',
        'q_hidden_author' => 'Pertanyaan ini disembunyikan oleh penulisnya',
        'q_hidden_flagged' => 'Pertanyaan dilaporkan sebagai spam atau disembunyikan',
        'q_hidden_other' => 'Pertanyaan ini disembunyikan',
        'q_notify_email' => 'Saya ingin menerima email ke alamat berikut jika seseorang menjawab atau mengomentari pertanyaan saya:',
        'q_notify_label' => 'Saya ingin menerima email jika seseorang menjawab atau mengomentari pertanyaan saya',
        'q_notify_x_label' => 'Saya ingin menerima email (^) ketika seseorang menjawab atau mengomentari pertanyaan saya',
        'q_tags_comma_label' => 'Tag - gunakan koma (,) sebagai pemisah:',
        'q_tags_label' => 'Tag - gunakan tanda hubung (-) untuk gabungkan kata, dan gunakan koma/spasi untuk tag berikutnya (maks 5 tag)',
        'q_title_label' => 'Pertanyaan Anda dalam satu kalimat:',
        'q_waiting_approval' => 'Pertanyaan ini menunggu persetujuan',
        'q_waiting_your_approval' => 'Pertanyaan ini menunggu persetujuan Anda',
        'q_your_waiting_approval' => 'Pertanyaan Anda akan segera ditinjau dan kemudian disetujui.',
        'recat_button' => 'Ubah kategori',
        'recat_popup' => 'Ubah kategori pertanyaan ini',
        'recat_q_title' => 'Ubah kategori pertanyaan',
        'reject_a_popup' => 'Tolak balasan ini',
        'reject_button' => 'tolak',
        'reject_c_popup' => 'Tolak komentar ini',
        'reject_q_popup' => 'Tolak pertanyaan ini',
        'remove_q_favorites' => 'Hapus pertanyaan ini dari favorit saya',
        'reopen_button' => 'buka kembali',
        'reopen_q_popup' => 'Buka kembali pertanyaan ini',
        'reply_button' => 'Balas',
        'reply_c_popup' => 'Balas komentar ini',
        'reshow_a_popup' => 'Tampilkan jawaban ini lagi',
        'reshow_button' => 'Tampilkan lagi',
        'reshow_c_popup' => 'Tampilkan komentar ini lagi',
        'reshow_q_popup' => 'Tampilkan pertanyaan ini lagi',
        'retag_button' => 'Ubah tag',
        'retag_cat_popup' => 'Ubah kategori atau tag pertanyaan ini',
        'retag_popup' => 'Ubah tag pertanyaan ini',
        'retag_q_title' => 'Ubah tag pertanyaan ini',
        'save_silent_label' => 'Simpan dan sembunyikan secara diam-diam bahwa ini telah diubah.',
        'select_popup' => 'Pilih jawaban terbaik',
        'select_text' => 'Jawaban terbaik',
        'show_1_comment' => 'Tampilkan komentar',
        'show_1_previous_comment' => 'Tampilkan komentar sebelumnya',
        'show_x_comments' => '^ Tampilkan komentar',
        'show_x_previous_comments' => '^ Tampilkan komentar sebelumnya',
        'unflag_button' => 'Unflag_button',
        'unflag_popup' => 'Hapus pesan spam yang Anda tambahkan',
        'unselect_popup' => 'Hapus pilihan',
        'x_answers_title' => '^ Jawaban',
        'your_answer_title' => 'Jawaban Anda',
        'your_comment_a' => 'Komentar Anda untuk jawaban ini:',
        'your_comment_q' => 'Komentar Anda untuk pertanyaan ini:',
    );


/*
    Omit PHP closing tag to help avoid accidental output
*/
